version: '3'

networks:
  default:
    external:
      name: ${NOMINEE_NETWORK}

services:
  haproxy:
    image: ${NOMINEE_DOCKER_REPO}/haproxyw:${IMAGE_VERSION}
    env_file:
      - ../conf/docker-compose.env
    ports:
      - 5000:5000
      - 5001:5001
      - 9999:9999