version: '3'

networks:
  default:
    external:
      name: ${NOMINEE_NETWORK}

services:
  node1:
    image: ${NOMINEE_DOCKER_REPO}/pgnominee:${IMAGE_VERSION}
    environment:
      - POSTGRES_PASSWORD=password
      - PG_NOMINEE_NODE_NAME=node1
      - PG_NOMINEE_NODE_ADDRESS=node1
      - PG_NOMINEE_CLUSTER_NAME=pgnominee
      - PG_NOMINEE_ETCD_ENDPOINTS=etcd1:2379,etcd2:2379,etcd3:2379
    ports:
      - 5411:5432

  node2:
    image: ${NOMINEE_DOCKER_REPO}/pgnominee:${IMAGE_VERSION}
    environment:
      - POSTGRES_PASSWORD=password
      - PG_NOMINEE_NODE_NAME=node2
      - PG_NOMINEE_NODE_ADDRESS=node2
      - PG_NOMINEE_CLUSTER_NAME=pgnominee
      - PG_NOMINEE_ETCD_ENDPOINTS=etcd1:2379,etcd2:2379,etcd3:2379
    ports:
      - 5412:5432

  node3:
    image: ${NOMINEE_DOCKER_REPO}/pgnominee:${IMAGE_VERSION}
    environment:
      - POSTGRES_PASSWORD=password
      - PG_NOMINEE_NODE_NAME=node3
      - PG_NOMINEE_NODE_ADDRESS=node3
      - PG_NOMINEE_CLUSTER_NAME=pgnominee
      - PG_NOMINEE_ETCD_ENDPOINTS=etcd1:2379,etcd2:2379,etcd3:2379
    ports:
      - 5413:5432